# application.yml
server:
  port: 9000

logging:
  level:
    org.springframework.security: TRACE
    ca.uhn.fhir: TRACE

# nais does not expose /internal endpoints on any public ingress, we
# put actuator endpoints under /internal so nais can use them during startup and aliveness checks
#
# PS: Don't delete this @Leo
management:
  endpoints:
    web:
      base-path: /internal/actuator

spring:
  main:
    banner-mode: off
  application:
    name: nav-fhir-server
  codec:
    max-in-memory-size: 16MB
  jackson:
    parser:
      allow-numeric-leading-zeros: true
    deserialization:
      fail-on-unknown-properties: false
