# application-dev.yml
logging:
  level:
    org.springframework.security: DEBUG
    ca.uhn.fhir: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth-fhir.ekstern.dev.nav.no"
          audiences:
            - "https://epj.ekstern.dev.nav.no"
            - "https://syk-inn.ekstern.dev.nav.no/fhir"

smart: # TODO must match https://github.com/navikt/nav-epj-auth-server well-knowns
  configuration: 
    issuer: "https://auth-fhir.ekstern.dev.nav.no"
    jwks_uri: "https://auth-fhir.ekstern.dev.nav.no/oauth2/jwks"
    authorization_endpoint: "https://auth-fhir.ekstern.dev.nav.no/oauth2/authorize"
    token_endpoint: "https://auth-fhir.ekstern.dev.nav.no/oauth2/token"
    introspection_endpoint: "https://auth-fhir.ekstern.dev.nav.no/oauth2/introspect"
    management_endpoint: "https://auth-fhir.ekstern.dev.nav.no/user/manage"
    revocation_endpoint: "https://auth-fhir.ekstern.dev.nav.no/user/revoke"
    user_access_brand_bundle: ""
    user_access_brand_identifier: ""
    grant_types_supported:
      - "authorization_code"
      - "client_credentials"
      - "refresh_token"
    scopes_supported:
      - "openid"
      - "profile"
      - "fhirUser"
      - "launch"
      - "patient/*.cruds"
      - "patient/*.*"
      - "encounter/*.cruds"
      - "encounter/*.*"
      - "user/*.cruds"
      - "user/*.*"
      - "offline_access"
    response_types_supported:
      - "code"
      - "token"
    capabilities:
      - "launch-ehr"
      - "launch-standalone"
      - "client-public"
      - "client-confidential-symmetric"
      - "client-confidential-asymmetric"
      - "sso-openid-connect"
      - "context-passthrough-banner"
      - "context-passthrough-style"
      - "context-ehr-patient"
      - "context-ehr-encounter"
      - "context-standalone-patient"
      - "context-standalone-encounter"
      - "permission-offline"
      - "permission-patient"
      - "permission-user"
      - "permission-v1"
      - "permission-v2"
      - "authorize-post"
    code_challenge_methods_supported:
      - "S256"