# application-local.yml
logging:
  level:
    org.springframework.security.oauth2: TRACE
    ca.uhn.fhir: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000"
          audiences:
            - "http://localhost:3000"
            - "http://localhost:3005"
            - "http://localhost:5173"

smart: # TODO must match https://github.com/navikt/nav-epj-auth-server well-knowns
  configuration:
    issuer: "http://localhost:9000"
    jwks_uri: "http://localhost:9000/oauth2/jwks"
    authorization_endpoint: "http://localhost:9000/oauth2/authorize"
    token_endpoint: "http://localhost:9000/oauth2/token"
    introspection_endpoint: "http://localhost:9000/oauth2/introspect"
    management_endpoint: "http://localhost:9000/oauth2/manage"
    revocation_endpoint: "http://localhost:9000/oauth2/revoke"
    user_access_brand_bundle: ""
    user_access_brand_identifier: ""
    grant_types_supported:
      - "authorization_code"
      - "client_credentials"
      - "refresh_token"
    scopes_supported:
      - "openid"
      - "profile"
      - "fhirUser"
      - "launch"
      - "patient/*.cruds"
      - "patient/*.*"
      - "encounter/*.cruds"
      - "encounter/*.*"
      - "user/*.cruds"
      - "user/*.*"
      - "offline_access"
    response_types_supported:
      - "code"
      - "token"
    capabilities:
      - "launch-ehr"
      - "launch-standalone"
      - "client-public"
      - "client-confidential-symmetric"
      - "client-confidential-asymmetric"
      - "sso-openid-connect"
      - "context-passthrough-banner"
      - "context-passthrough-style"
      - "context-ehr-patient"
      - "context-ehr-encounter"
      - "context-standalone-patient"
      - "context-standalone-encounter"
      - "permission-offline"
      - "permission-patient"
      - "permission-user"
      - "permission-v1"
      - "permission-v2"
      - "authorize-post"
    code_challenge_methods_supported:
      - "RS256"