# application-local.yml
logging:
  level:
    org.springframework.security: TRACE
    ca.uhn.fhir: TRACE

authorization:
  issuer: "http://localhost:9000"
  client:
    redirect-uri: "http://localhost:5173/samarbeidspartner/sykmelding/fhir"

cors:
  allowed-origin-patterns:
    - "http://localhost:[*]"
    - "http://127.0.0.1:[*]"