server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  main:
    banner-mode: off
  application:
    name: nav-fhir-server
  codec:
    max-in-memory-size: 16MB
  jackson:
    parser:
      allow-numeric-leading-zeros: true
    deserialization:
      fail-on-unknown-properties: false
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        endpoint:
          token-uri: /v1/oauth2/token
          authorization-uri: /v1/oauth2/authorize
          jwk-set-uri: /v1/oauth2/jwks
          token-introspection-uri: /v1/oauth2/introspect
          token-revocation-uri: /v1/oauth2/revoke
          oidc:
            logout-uri: /v1/connect/logout
            client-registration-uri: /v1/connect/register
            user-info-uri: /v1/userinfo